// vim: ft=groovy et ts=2 sw=2:

node('java11') {
    ansiColor('xterm') {
      stage("Building app") {
            container('java11') {
              // Checkout repo
              checkout scm
              // Generating build info
              commit_hash = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
              build_tag = commit_hash + "_" + env.BUILD_NUMBER
              // Building jar
              sh """
                cd ${env.WORKSPACE}/api-gateway
                java --version
                pwd
                mvn clean install
              """
            }
          }
      stage("Building container") {
            container('kaniko') {
              // Building and pushing the container
              sh """
                ls
                /kaniko/executor --dockerfile Dockerfile --context `pwd` --destination ${env.DOCKER_HUB_URL}/api-gateway:${build_tag}
                echo {\\"image_name\\" : \\"api-gateway\\", \\"image_tag\\" : \\"${build_tag}\\"} > ${env.WORKSPACE}/metadata.json
              """
              archiveArtifacts "metadata.json"
            }

        }
    }
}