package org.swasth.common.exception;

public enum ErrorCodes {
    CLIENT_ERR_INVALID_PARTICIPANT_DETAILS,
    SERVICE_UNAVAILABLE,
    INTERNAL_SERVER_ERROR,
    SERVER_ERR_GATEWAY_TIMEOUT,
    CLIENT_ERR_INVALID_SEARCH,
    CLIENT_ERR_INVALID_CORRELATION_ID,
    CLIENT_ERR_INVALID_WORKFLOW_ID
}
