package org.swasth.common.exception;

public enum ErrorCodes {
    ERR_INVALID_PARTICIPANT_CODE,
    ERR_INVALID_PARTICIPANT_DETAILS,
    ERR_SERVICE_UNAVAILABLE,
    INTERNAL_SERVER_ERROR,
    SERVER_ERR_GATEWAY_TIMEOUT,
    ERR_INVALID_SEARCH,
    ERR_INVALID_CORRELATION_ID,
    ERR_INVALID_WORKFLOW_ID,
    ERR_INVALID_PAYLOAD,
    ERR_INVALID_NOTIFICATION_TOPIC_CODE,
    ERR_INVALID_NOTIFICATION_REQ,
    ERR_INVALID_SUBSCRIPTION_ID,
    ERR_INVALID_JWT,
    ERR_INVALID_IDENTITY,
    ERR_PAYOR_SYSTEM,
    ERR_INVALID_LINK,
    ERR_UPDATE_PARTICIPANT_DETAILS,
    ERR_INVALID_ONBOARD_STATUS,
    ERR_MAXIMUM_LINK_REGENERATE,
    ERR_INVALID_CERTIFICATE,
    ERR_INVALID_REQUEST,
    ERR_ACCESS_DENIED,
    ERR_INVALID_USER_ID,
    ERR_INVALID_USER_DETAILS
}
