package com.oss.apigateway.exception;

public enum ErrorCodes {
    CLIENT_ERR_INVALID_PAYLOAD,
    CLIENT_ERR_INVALID_REQ_PROTECTED,
    CLIENT_ERR_INVALID_SENDER,
    CLIENT_ERR_INVALID_RECIPIENT,
    INTERNAL_SERVER_ERROR,
    SERVER_ERROR
}
