package com.oss.apigateway.exception;

public enum ErrorCodes {
    CLIENT_ERR_INVALID_PAYLOAD,
    CLIENT_ERR_WRONG_ENCODED_PROTECTED,
    CLIENT_ERR_INVALID_REQ_ID,
    CLIENT_ERR_INVALID_WORKFLOW_ID,
    CLIENT_ERR_INVALID_SENDER,
    CLIENT_ERR_INVALID_RECIPIENT,
    CLIENT_ERR_INVALID_CALLER_ID,
    INTERNAL_SERVER_ERROR
}
