// vim: ft=groovy et ts=2 sw=2:
node {
  try {
    stage('Checkout') {
      checkout scm
    }
    stage('Environment') {
      sh 'git --version'
      echo "Branch: ${env.BRANCH_NAME}"
      sh 'docker -v'
      sh 'printenv'
    }

    stage('Deploy'){
      if(env.BRANCH_NAME == 'demo-app'){
contaner('kaniko'){
/kaniko/executor --dockerfile Dockerfile --context `pwd` --destination ${env.DOCKER_HUB_URL}/api-gateway:${build_tag}
                echo {\\"image_name\\" : \\"api-gateway\\", \\"image_tag\\" : \\"${build_tag}\\"} > ${env.WORKSPACE}/metadata.json
archiveArtifacts "metadata.json"
}
      
}
    }
  }
  catch (err) {
    throw err
  }
}
