// vim: ft=groovy et ts=2 sw=2:

node {
   try{
    ansiColor('xterm') {
      stage("SCM Checkout"){
            checkout scm
}

      stage("Building container") {
            container('kaniko') {
              // Building and pushing the container
              sh """
                echo ${env.WORKSPACE}
                cd ${env.WORKSPACE}/demo-app
                pwd
                /kaniko/executor --dockerfile Dockerfile --context `pwd` --destination ${env.DOCKER_HUB_URL}/demo-app:${build_tag}
                echo {\\"image_name\\" : \\"demo-app\\", \\"image_tag\\" : \\"${build_tag}\\"} > ${env.WORKSPACE}/metadata.json
              """
              archiveArtifacts "metadata.json"
            }

        }
    }}
catch (err){
throw (err)
}
}
