export default {
  WELCOME: 'Welcome to the HCX beneficiary app',
  SIGNIN: 'Please sign in to your account.',
  ENTER_MOBILE_NUMBER: 'Enter your mobile no. to sign in :',
  TEN_DIGIT: '10-digit mobile no.',
  SEND_OTP: 'Send OTP',
  OTP_SENT: 'OTP sent to below mobile number',
  ENTER_OTP: 'Enter OTP',
  SIX_DIGIT: 'Enter 6-digit OTP',
  VERIFY_OTP_BUTTON: 'Verify OTP',
  RESEND_OTP_BUTTON: 'Resend OTP',
  ADD_PROFILE_DETAILS: 'Add profile details :',
  USERS_NAME: "User's name",
  ENTER_YOUR_NAME: 'Enter your name',
  MOBILE: 'Mobile number *',
  ENTER_MOBILE: 'Enter mobile number',
  EMAILID: 'Email ID',
  ENTER_EMAIL_ADDRESS: 'Enter email address',
  ADD_INSURANCE_PLAN: 'Add insurance plan :',
  PAYOR_DETAILS: 'Payor Details *',
  INSURANCE_ID: 'Insurance ID *',
  ADD_ANOTHER: '+ Add another',
  SAVE_PROFILE_DETAILS: 'Save profile details',
  WELCOME_TEXT: 'Welcome,',
  SCAN_QRCODE: 'Scan provider QR code to verify coverage',
  SUBMIT_NEW_CLAIM: 'Click here to submit a new claim',
  YOUR_ACTIVE_CYCLE: 'Your active claim cycle',
  COVERAGE_ELIGIBILITY_REQUEST_HEADING: 'New coverage eligibility request',
  PROVIDER_NAME: 'Provider name:',
  PARTICIPANT_CODE: 'Participant code:',
  SERVICE_TYPE: 'Treatment/Service type: *',
  SELECT_INSURANCE_PLAN: 'Select insurance plan: *',
  INSURANCE_DETAILS: 'Insurance details',
  CHECK_COVERAGE_ELIGIBILITY: 'Check coverage eligibility',
  PROVIDE_DETAILS_FOR_NEW_CLAIM: 'Provide details to initiate claim request',
  INITIATE_CLAIM_REQUEST: 'Initiate claim request',
};
