export default {
  WELCOME: 'Welcome to the HCX beneficiary app',
  SIGNIN: 'Please sign in to your account.',
  ENTER_MOBILE_NUMBER: 'Enter your mobile no. to sign in :',
  TEN_DIGIT: '10-digit mobile no.',
  SEND_OTP: 'Send OTP',
  OTP_SENT: 'OTP sent to below mobile number',
  ENTER_OTP: 'Enter OTP',
  SIX_DIGIT: 'Enter 6-digit OTP',
  VERIFY_OTP_BUTTON: 'Verify OTP',
  RESEND_OTP_BUTTON: 'Resend OTP',
  ADD_PROFILE_DETAILS: 'Add profile details :',
  USERS_NAME: "User's name",
  ENTER_YOUR_NAME: 'Enter your name',
  MOBILE: 'Mobile number *',
  ENTER_MOBILE: 'Enter mobile number',
  EMAILID: 'Email ID',
  ENTER_EMAIL_ADDRESS: 'Enter email address',
  ADD_INSURANCE_PLAN: 'Add insurance plan :',
  PAYOR_DETAILS: 'Payor Name *',
  INSURANCE_ID: 'Insurance ID *',
  ADD_ANOTHER: '+ Add another',
  SAVE_PROFILE_DETAILS: 'Save profile details',
  WELCOME_TEXT: 'Welcome,',
  SCAN_QRCODE: 'Scan provider QR code to initiate coverage eligibility request',
  SUBMIT_NEW_CLAIM: 'Click here to submit a new claim',
  YOUR_ACTIVE_CYCLE: 'Your active requests',
  COVERAGE_ELIGIBILITY_REQUEST_HEADING: 'New coverage eligibility request',
  PROVIDER_NAME: 'Provider name:',
  PARTICIPANT_CODE: 'Participant code:',
  SERVICE_TYPE: 'Treatment/Service Category: *',
  SELECT_INSURANCE_PLAN: 'Select insurance plan: *',
  INSURANCE_DETAILS: 'Insurance details',
  INITIATE_COVERAGE_ELIGIBILITY: 'Initiate coverage eligibility request',
  PROVIDE_DETAILS_FOR_NEW_CLAIM: 'Provide details to initiate claim request',
  INITIATE_CLAIM_REQUEST: 'Initiate claim request',
  NEW_CLAIM_REQUEST: 'New claim request',
  TREATMENT_AND_BILLING_DETAILS: 'Treatment & billing details : *',
  BILL_AMOUNT: 'Bill amount : *',
  SUPPORTING_DOCS: 'Supporting documents : *',
  DOC_TYPE: 'Document type :',
  UPLOAD_DOCS: 'Select documents',
  DELETE: 'Delete',
  SUBMIT_CLAIM: 'Submit Pre-Auth Request',
  NEW_PREAUTH_REQUEST: 'New pre-auth request',
  ESTIMATED_BILL_AMOUNT: 'Estimated bill amount :',
  SUBMIT_PREAUTH: 'Submit pre-auth',
  CLAIM_REQUEST_DETAILS: 'Request details :',
  NEXT_STEP: 'Next step :',
  POLICYHOLDER_CONSENT: 'Beneficiary consent :',
  ENTER_OTP_TO_VERIFY_CLAIM:
    'Please enter OTP shared by payor to verify claim :',
  INITIATE_PREAUTH_REQUEST: 'Initiate pre-auth request',
  INITIATE_NEW_CLAIM_REQUEST: 'Initiate new claim request',
  PROCEED: 'Proceed',
};
