name: Onboarding App Deploy to S3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        default: dev
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build the app
        run: |
          cd onboarding-app
          npm ci
          npm run build

      - name: Configure AWS credentials
        run: |
         cd onboarding-app
         aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to S3
        run: |
          cd onboarding-app
          aws s3 sync build/ s3://${{ github.event.inputs.environment }}-hcx-onboarding --acl public-read --region ${{ secrets.AWS_REGION }}